#!/usr/bin/env bash
# check-mirrors.sh — test mirror reachability and write fastest to .mirrors.env
#
# Usage:
#   source scripts/check-mirrors.sh          # auto-select, export vars
#   ./scripts/check-mirrors.sh               # auto-select, write .mirrors.env
#   ./scripts/check-mirrors.sh --pypi-only   # test only PyPI mirrors
#   ./scripts/check-mirrors.sh --docker-only # test only Docker base images
#   ./scripts/check-mirrors.sh --show        # print current selection

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MIRRORS_ENV="$PROJECT_DIR/.mirrors.env"
TIMEOUT=4

# ─── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

# All log functions write to stderr so stdout stays clean for captured output
log_ok()   { echo -e "${GREEN}  ✓${RESET} $*" >&2; }
log_fail() { echo -e "${RED}  ✗${RESET} $*" >&2; }
log_info() { echo -e "${CYAN}  →${RESET} $*" >&2; }
log_head() { echo -e "\n${BOLD}$*${RESET}" >&2; }

# ─── Show current selection ───────────────────────────────────────────────────
if [[ "${1:-}" == "--show" ]]; then
  if [[ -f "$MIRRORS_ENV" ]]; then
    echo -e "${BOLD}Current mirror selection ($MIRRORS_ENV):${RESET}"
    cat "$MIRRORS_ENV"
  else
    echo "No .mirrors.env found. Run ./scripts/check-mirrors.sh to auto-select."
  fi
  exit 0
fi

# ─── PyPI mirrors ─────────────────────────────────────────────────────────────
PYPI_MIRRORS=(
  "https://pypi.org/simple"
  "https://pypi.tuna.tsinghua.edu.cn/simple"
  "https://pypi.mirrors.ustc.edu.cn/simple"
  "https://mirrors.aliyun.com/pypi/simple"
  "https://pypi.doubanio.com/simple"
  "https://mirrors.bfsu.edu.cn/pypi/web/simple"
)

# ─── Docker base images ────────────────────────────────────────────────────────
DOCKER_IMAGES=(
  "python:3.12-slim"
  "registry.cn-hangzhou.aliyuncs.com/library/python:3.12-slim"
  "ccr.ccs.tencentyun.com/library/python:3.12-slim"
  "hub.c.163.com/library/python:3.12-slim"
)

# ─── uv installer URLs ─────────────────────────────────────────────────────────
UV_INSTALL_URLS=(
  "https://astral.sh/uv/install.sh"
  "https://raw.githubusercontent.com/astral-sh/uv/main/scripts/install.sh"
)

# ─── Test functions ───────────────────────────────────────────────────────────
test_url() {
  local url="$1"
  curl -fsS --head --max-time "$TIMEOUT" "$url" &>/dev/null
}

test_docker_image() {
  local image="$1"
  # Pull manifest without downloading the full image
  docker manifest inspect "$image" &>/dev/null 2>&1
}

find_fastest_pypi() {
  log_head "Testing PyPI mirrors..."
  for mirror in "${PYPI_MIRRORS[@]}"; do
    if test_url "$mirror"; then
      log_ok "$mirror"
      echo "$mirror"
      return 0
    else
      log_fail "$mirror"
    fi
  done
  log_info "All mirrors unreachable — defaulting to https://pypi.org/simple"
  echo "https://pypi.org/simple"
}

find_fastest_docker_image() {
  log_head "Testing Docker base images..."
  if ! command -v docker &>/dev/null; then
    log_info "Docker not installed — skipping Docker mirror check"
    echo "python:3.12-slim"
    return 0
  fi
  for image in "${DOCKER_IMAGES[@]}"; do
    if test_docker_image "$image"; then
      log_ok "$image"
      echo "$image"
      return 0
    else
      log_fail "$image"
    fi
  done
  log_info "No Docker registry accessible — using python:3.12-slim (may need docker login)"
  echo "python:3.12-slim"
}

find_fastest_uv_installer() {
  log_head "Testing uv installer URLs..."
  for url in "${UV_INSTALL_URLS[@]}"; do
    if test_url "$url"; then
      log_ok "$url"
      echo "$url"
      return 0
    else
      log_fail "$url"
    fi
  done
  log_info "uv installer URLs unreachable — will install via pip fallback"
  echo "pip"
}

# ─── Main ─────────────────────────────────────────────────────────────────────
MODE="${1:-all}"

SELECTED_PYPI=""
SELECTED_DOCKER_IMAGE=""
SELECTED_UV_INSTALLER=""

if [[ "$MODE" != "--docker-only" ]]; then
  SELECTED_PYPI="$(find_fastest_pypi)"
fi

if [[ "$MODE" != "--pypi-only" ]]; then
  SELECTED_DOCKER_IMAGE="$(find_fastest_docker_image)"
  SELECTED_UV_INSTALLER="$(find_fastest_uv_installer)"
fi

# ─── Write .mirrors.env ──────────────────────────────────────────────────────
{
  echo "# Auto-generated by check-mirrors.sh — $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "# Re-run ./scripts/check-mirrors.sh to refresh"
  [[ -n "$SELECTED_PYPI" ]]           && echo "UV_INDEX_URL=$SELECTED_PYPI"
  [[ -n "$SELECTED_PYPI" ]]           && echo "PIP_INDEX_URL=$SELECTED_PYPI"
  [[ -n "$SELECTED_DOCKER_IMAGE" ]]   && echo "DOCKER_BASE_PYTHON=$SELECTED_DOCKER_IMAGE"
  [[ -n "$SELECTED_UV_INSTALLER" ]]   && echo "UV_INSTALL_URL=$SELECTED_UV_INSTALLER"
} > "$MIRRORS_ENV"

echo -e "\n${GREEN}${BOLD}Mirror selection written to .mirrors.env${RESET}"
cat "$MIRRORS_ENV"

# Export for the current shell session if sourced
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  # shellcheck source=/dev/null
  set -a; source "$MIRRORS_ENV"; set +a
  echo -e "${CYAN}Variables exported to current shell.${RESET}"
fi
